# Headless e2e smoke: compile addon resources, launch Dota in -tools mode with
# the e2e harness engaged, let the fake-client Pudges hook each other until a
# team reaches the (overridden) kill target, then scan console.log for script
# errors and the [E2E] WIN marker. Best autonomous approximation of a playtest.
#
# The whole run is also screen-recorded to C:\pw-record.mp4 (ffmpeg gdigrab,
# archer-wars vm-smoke-record.ps1 pattern). Tools mode opens the Asset Browser
# ON TOP of the game window, so without intervention the recording (and the
# screenshots) show a file browser, not the match — the poll loop minimizes
# "Asset Browser" and pins the game window topmost every cycle. Window lookup
# is by TITLE with CharSet.Unicode (class lookup returns 0; ANSI marshaling
# silently breaks FindWindowW — both verified on archer-wars runs 5/6).
#
# MAP: the generated pudge_wars.vmap (mapgen/ + scripts/vm-buildmap.ps1) —
# flat court, central river of real water, two facing spawn rows. vm.sh smoke
# builds it before staging this script.
#
# Must run INSIDE the active console session (session 1) so the datacenter GPU
# initializes a DX11 device -- drive it via a scheduled task with an Interactive
# principal, not directly over SSH (session 0 has no display head).
param(
  [string]$Dota   = "C:\steamcmd\steamapps\common\dota 2 beta",
  [string]$Addon  = "pudge_wars",
  [string]$Map    = "pudge_wars",  # generated by mapgen (vm-buildmap.ps1)
  [int]$Kills     = 25,       # e2e-only override (real matches stay KILLS_TO_WIN=10).
                              # Run 34: lethal hooks ended a 10-kill match in 97 s —
                              # too short for the meteor/dodge/shield gates to sample.
                              # 25 kills ≈ 4 min of play; the win PATH is identical.
  [int]$LoadSeconds = 1350    # GPU/asset warmup (~2min) + a full 10-kill match at the
                              # observed pace (run 18: ~80s/kill with heals + escapes).
                              # Early-exit on WIN keeps green runs short.
)
$ErrorActionPreference = "Continue"
$win64  = Join-Path $Dota "game\bin\win64"
$log    = Join-Path $Dota "game\dota\console.log"
$result = "C:\pw-smoke-result.txt"
$video  = "C:\pw-record.mp4"

"smoke start $(Get-Date -Format o)" | Out-File $result -Encoding utf8

# fresh console log + old recording
if (Test-Path $log)   { Remove-Item $log -Force }
if (Test-Path $video) { Remove-Item $video -Force }

# 1) resource compile the addon (panorama/particles; no map of our own yet)
$rc = Join-Path $win64 "resourcecompiler.exe"
& $rc -a -i "$Dota\content\dota_addons\$Addon\*" 2>&1 | Select-Object -Last 10 | Out-String | Add-Content $result

# 2) start the screen recording BEFORE the game launches so load + match are
#    all captured. FRAGMENTED mp4 (frag_keyframe+empty_moov) on purpose: the
#    smoke early-exits the moment [E2E] WIN lands, and a plain mp4 killed
#    mid-write loses its trailer and is unplayable — a fragmented one survives
#    Stop-Process at any point. -t is the fallback bound if the run goes long.
#    ffmpeg is on PATH on the VM (installed for archer-wars recorded smokes).
$ff = $null
if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
  # +120, not +30: the -t is only the FALLBACK bound (the poll loop stops
  # ffmpeg ~10s after WIN), and run 22's match won at LoadSeconds+8 — the
  # fallback cut the recording just before the victory banner.
  $recSeconds = $LoadSeconds + 120
  # 24 fps since run 14: at 15 fps the flying hook chain smears into a faint
  # streak (frame audit) — 24 makes the signature skillshot legible on review.
  $ffArgs = @(
    "-y","-f","gdigrab","-framerate","24","-i","desktop",
    # Downscale to 1280 wide: a full 900s desktop grab at 24fps was 245MB and
    # the IAP-tunnel pull truncated it twice (run 15) — half the pixels, same
    # review value.
    "-vf","scale=1280:-2",
    "-t","$recSeconds","-c:v","libx264","-preset","ultrafast","-crf","31",
    "-pix_fmt","yuv420p","-movflags","frag_keyframe+empty_moov",$video
  )
  $ff = Start-Process -FilePath "ffmpeg" -ArgumentList $ffArgs -PassThru -WindowStyle Hidden
  "recording pid $($ff.Id) for ${recSeconds}s -> $video" | Add-Content $result
} else {
  "ffmpeg NOT FOUND on PATH -- no recording this run" | Add-Content $result
}

# 3) launch tools mode, auto-load the custom game with the harness engaged and
#    a bounded win threshold.
$args = @(
  "-novid","-tools","-addon",$Addon,"-condebug","-nominidumps","-nocrashdialog",
  "-windowed","-w","1280","-h","720",
  # Locked camera on the host hero -- the harness parks that hero mid-river
  # as an invisible tripod, so the recording frames both banks (the only
  # camera technique that reliably moves the tools client in a match run).
  "+dota_camera_lock","1",
  # Zoom the locked camera out so the WHOLE playfield fits the frame: shop
  # pads (x=+-1900), lurk-depth roamers and gift spawns are all on camera.
  # Default distance (~1200) framed only x in [-1200,1200] -- the run-24
  # frames showed shopping and deep roam happening entirely off-screen.
  "+dota_camera_distance","2400",
  "+pudge_wars_e2e","1","+pudge_wars_e2e_kills","$Kills",
  "+dota_launch_custom_game","$Addon","$Map"
)
# Diagnostic runs only: `touch C:\pw-fxtest.flag` (over SSH) before triggering
# the task to draw the spec-011 chain-FX candidate panel. File flag, not env:
# scheduled-task sessions do not inherit the SSH session's environment.
if (Test-Path "C:\pw-fxtest.flag") {
  # Insert BEFORE the final "+dota_launch_custom_game <addon> <map>" triple —
  # anything spliced inside it is eaten as the addon name and nothing loads
  # (run 30: "harness never engaged").
  $args = $args[0..($args.Length-4)] + @("+pudge_wars_fxtest","1") + $args[($args.Length-3)..($args.Length-1)]
}
$proc = Start-Process -FilePath (Join-Path $win64 "dota2.exe") -ArgumentList $args -PassThru

# Visual evidence: capture a full-screen PNG every 20s while the game runs.
# Requires the interactive session (same reason the whole script does).
$shots = "C:\pw-shots"
New-Item -ItemType Directory -Force -Path $shots | Out-Null
Remove-Item "$shots\*.png" -Force -ErrorAction SilentlyContinue
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Window wrangling so the recording sees the GAME, not the Asset Browser.
Add-Type @"
using System;
using System.Runtime.InteropServices;
public static class PWWin {
  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);
  // CharSet.Unicode is REQUIRED: default ANSI marshaling silently breaks the
  // W-suffixed API (title never matches, returns 0).
  [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern IntPtr FindWindowW(string cls, string title);
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int cmd);
  [DllImport("user32.dll")] public static extern bool SetWindowPos(IntPtr hWnd, IntPtr after, int x, int y, int w, int h, uint flags);
}
"@
$HWND_TOPMOST = [IntPtr](-1)
$SWP_NOSIZE_NOMOVE = 0x0003
$SW_MINIMIZE = 6

$elapsed = 0
$winSeen = $false
while ($elapsed -lt $LoadSeconds) {
  Start-Sleep -Seconds 20
  $elapsed += 20
  # Every cycle: bury the Asset Browser, surface the game window. Tools mode
  # re-raises the browser on some reloads, so this is a loop, not a one-shot.
  $ab = [PWWin]::FindWindowW($null, "Asset Browser")
  if ($ab -ne [IntPtr]::Zero) { [PWWin]::ShowWindow($ab, $SW_MINIMIZE) | Out-Null }
  $game = [PWWin]::FindWindowW($null, "Dota 2")
  if ($game -eq [IntPtr]::Zero) {
    $p = Get-Process dota2 -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowHandle -ne 0 } | Select-Object -First 1
    if ($p) { $game = $p.MainWindowHandle }
  }
  if ($game -ne [IntPtr]::Zero) {
    [PWWin]::SetWindowPos($game, $HWND_TOPMOST, 0, 0, 0, 0, $SWP_NOSIZE_NOMOVE) | Out-Null
    [PWWin]::SetForegroundWindow($game) | Out-Null
  }
  if ($elapsed -eq 60) { "window push t60: ab=$ab game=$game" | Add-Content $result }
  try {
    $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
    $bmp = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
    $gfx = [System.Drawing.Graphics]::FromImage($bmp)
    $gfx.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
    $bmp.Save((Join-Path $shots ("shot_{0:d3}s.png" -f $elapsed)))
    $gfx.Dispose(); $bmp.Dispose()
  } catch { "screenshot failed at ${elapsed}s: $_" | Add-Content $result }
  # Early exit once the win marker lands -- no reason to bill for the rest.
  if ((Test-Path $log) -and (Select-String -Path $log -Pattern "\[E2E\] WIN" -Quiet)) {
    "win marker seen at ${elapsed}s -- stopping early" | Add-Content $result
    $winSeen = $true
    Start-Sleep -Seconds 10   # let the post-win lines flush to the log
    break
  }
}
"screenshots: $((Get-ChildItem $shots -Filter *.png).Count)" | Add-Content $result
"process alive at kill: $(-not $proc.HasExited)" | Add-Content $result
if (-not $proc.HasExited) { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }

# Close out the recording. Fragmented mp4 tolerates a hard stop; give ffmpeg a
# few seconds to flush the last fragment first.
if ($ff -and -not $ff.HasExited) {
  Start-Sleep -Seconds 5
  Stop-Process -Id $ff.Id -Force -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 2
}
if (Test-Path $video) {
  "recording done: $((Get-Item $video).Length) bytes" | Add-Content $result
} else {
  "NO recording produced" | Add-Content $result
}

# 3) scan console log against the marker contract (docs/specs/MARKERS.md)
$fail = $null
if (Test-Path $log) {
  $lines = Get-Content $log
  "console.log lines: $($lines.Count)" | Add-Content $result

  "--- SCRIPT ERRORS ---" | Add-Content $result
  $errors = $lines | Select-String -Pattern "Script Error|attempt to|nil value|stack traceback" | ForEach-Object { $_.Line }
  $errors | Add-Content $result

  "--- E2E MARKERS ---" | Add-Content $result
  ($lines | Select-String -Pattern "\[E2E\]" | ForEach-Object { $_.Line }) | Add-Content $result

  "--- HOOK / GAME MARKERS ---" | Add-Content $result
  ($lines | Select-String -Pattern "\[HOOK\]|\[ROT\]|\[RIVER\]|\[SHOP\]|\[MATCH\]" | ForEach-Object { $_.Line } | Select-Object -First 60) | Add-Content $result

  "--- GIFT / MOTION / TACTICS MARKERS ---" | Add-Content $result
  ($lines | Select-String -Pattern "\[GIFT\]|\[MOTION\]|\[DODGE\]|\[RETREAT\]|\[SKILL\]" | ForEach-Object { $_.Line } | Select-Object -First 80) | Add-Content $result
  "--- CHAIN / ROAM / HAZARD / METEOR / TRIP MARKERS (specs 011-014) ---" | Add-Content $result
  ($lines | Select-String -Pattern "\[CHAIN\]|\[ROAM\]|\[HAZARD\]|\[METEOR\]|\[SHOP\] trip" | ForEach-Object { $_.Line } | Select-Object -First 80) | Add-Content $result

  "--- GAMERULES STATE ---" | Add-Content $result
  ($lines | Select-String -Pattern "entering state 'DOTA_GAMERULES" | ForEach-Object { $_.Line }) | Add-Content $result

  $logText = $lines -join "`n"
  if ($errors.Count -gt 0)                { $fail = "script errors in console.log ($($errors.Count) lines)" }
  elseif ($logText -notmatch "\[E2E\] harness engaged") { $fail = "harness never engaged (convar/addon load problem)" }
  elseif ($logText -notmatch "\[E2E\] WIN")             { $fail = "no [E2E] WIN marker -- bots never reached $Kills kills" }
  # Full-system gates (2026-07-27): a WIN off hooks alone previously passed
  # while Rot, Flesh Heap and the shop shipped with ZERO tier-2 evidence.
  elseif ($logText -notmatch "\[ROT\] tick")        { $fail = "no [ROT] tick -- Rot never damaged anyone" }
  elseif ($logText -notmatch "\[FLESH\] stack")     { $fail = "no [FLESH] stack -- Flesh Heap never grew" }
  elseif ($logText -notmatch "\[SHOP\] purchased")  { $fail = "no [SHOP] purchased -- bots never bought an item" }
  # Gameplay-shape gates (2026-07-27, specs 006/007): run 12 was marker-green
  # while the video showed two motionless stacks, no river prizes and no
  # visible economy. These gates make that class of run FAIL.
  elseif ($logText -notmatch "\[GIFT\] spawned")    { $fail = "no [GIFT] spawned -- river gift system never fired" }
  elseif ($logText -notmatch "\[GIFT\] redeemed")   { $fail = "no [GIFT] redeemed -- bots never hooked a chest home" }
  elseif ($logText -match  "\[MOTION\] STUCK")      { $fail = "[MOTION] STUCK -- a bot stood still a full window (run-12 class failure)" }
  # Specs 008-010 gates (run-14 field report).
  elseif ($logText -match  "\[RIVER\] audit lingerers [1-9]") { $fail = "river lingerers -- someone parked in the water past grace (spec 008)" }
  elseif (($lines | Select-String -Pattern "\[RIVER\] audit lingerers 0").Count -lt 2) { $fail = "river linger audit missing -- spec 008 liveness not measured" }
  elseif ($logText -notmatch "\[DODGE\] sidestep")  { $fail = "no [DODGE] -- the reflex layer is dead code (spec 009)" }
  # Run 35: lethal hooks made damage bimodal (full or dead) — low-HP states
  # are rare, so retreat/iron-gut fail only when the harness logged the
  # OPPORTUNITY ([HP] low / [HP] critical) and the behavior still never fired.
  elseif (($logText -match "\[HP\] low") -and ($logText -notmatch "\[RETREAT\] bot")) { $fail = "bots got wounded but never retreated (spec 009)" }
  elseif ($logText -notmatch "\[SKILL\] used pudge_wars_vanish")   { $fail = "vanish never used (spec 010)" }
  elseif (($logText -match "\[HP\] critical") -and ($logText -notmatch "\[SKILL\] used pudge_wars_iron_gut")) { $fail = "iron-gut moment came and the button was never pressed (spec 010)" }
  elseif ($logText -notmatch "\[SKILL\] used pudge_wars_sprint")   { $fail = "sprint never used (spec 010)" }
  elseif (($lines | Select-String -Pattern "\[MOTION\] audit").Count -lt 12) {
    $fail = "motion audit thin ($(($lines | Select-String -Pattern '\[MOTION\] audit').Count) lines < 12) -- liveness not measured across the match"
  }
  # Specs 011-014 gates (2026-07-29 field report: chains, dynamism, gifts seen, shop trips, meteor).
  elseif (($lines | Select-String -Pattern "\[CHAIN\] attached").Count -lt 20) { $fail = "hook chain thin -- <20 [CHAIN] attached (spec 011)" }
  elseif ([Math]::Abs((($lines | Select-String -Pattern "\[CHAIN\] attached").Count) - (($lines | Select-String -Pattern "\[CHAIN\] released").Count)) -gt 2) {
    $fail = "chain attach/release imbalance -- leaked chain particles (spec 011)"
  }
  elseif (($lines | Select-String -Pattern "\[ROAM\] waypoint").Count -lt 40) { $fail = "roam thin -- <40 [ROAM] waypoints, movement not dynamic (spec 012)" }
  elseif ($logText -notmatch "\[HAZARD\] tick")     { $fail = "no [HAZARD] tick -- river hazard never fired (spec 012)" }
  elseif ($logText -match "\[HAZARD\] lethal")      { $fail = "[HAZARD] lethal -- the river killed someone, 1 HP floor broke (spec 012)" }
  elseif (($lines | Select-String -Pattern "\[SHOP\] trip arrive").Count -lt 6) { $fail = "shop trips thin -- <6 [SHOP] trip arrive (spec 013)" }
  # Spec 016 (2026-08-03): the host pudge PLAYS on camera — its items must be
  # bought at the pad (HUD shows the purchase), never conjured by script.
  elseif ($logText -notmatch "\[SHOP\] purchased \S+ by 0") { $fail = "host pudge never bought an item (spec 016)" }
  # Spec 013 visibility fix (2026-08-05): pad visuals must be created at the
  # horn, with clients connected — constructor-time FX render for nobody.
  elseif ($logText -notmatch "\[SHOP\] pads drawn 2") { $fail = "no [SHOP] pads drawn 2 -- pad visuals not created at the horn (spec 013 visibility)" }
  elseif ($logText -notmatch "\[METEOR\] cast")     { $fail = "no [METEOR] cast -- meteor item never used (spec 013)" }
  elseif ($logText -notmatch "\[METEOR\] impact victims [1-9]") { $fail = "meteor never hit anyone (spec 013)" }
  elseif (($lines | Select-String -Pattern "\[GIFT\] dwell ok").Count -lt 3)   { $fail = "gift dwell thin -- <3 [GIFT] dwell ok (spec 014)" }
  elseif ($logText -match "\[GIFT\] dwell violation") { $fail = "gift dwell violation -- a bot sniped a chest young (spec 014)" }
  elseif (($lines | Select-String -Pattern "\[GIFT\] drifting").Count -lt 3)   { $fail = "gift drift thin -- <3 [GIFT] drifting (spec 014 rev 2: chest must float)" }
  elseif (-not (Test-Path $video))                  { $fail = "no recording produced (ffmpeg missing or died)" }
  else {
    # Final inventory audit must be n/n: every living bot holds >=1 item.
    $audits = $lines | Select-String -Pattern "\[SHOP\] audit bots_with_items (\d+)/(\d+)"
    if ($audits.Count -eq 0) { $fail = "no [SHOP] audit lines -- inventory never verified" }
    else {
      $last = $audits[-1]
      $n = [int]$last.Matches[0].Groups[1].Value
      $m = [int]$last.Matches[0].Groups[2].Value
      if ($n -lt $m) { $fail = "final [SHOP] audit $n/$m -- $($m - $n) bot(s) ended the match itemless" }
    }
  }
} else {
  $fail = "NO console.log produced (launch may have failed)"
  $fail | Add-Content $result
}

if ($fail) { "SMOKE FAIL: $fail" | Add-Content $result }
else       { "SMOKE PASS: win marker present, zero script errors" | Add-Content $result }
"smoke done $(Get-Date -Format o)" | Add-Content $result
# End-of-run hard gate: fail (non-zero) only after all evidence is in $result.
if ($fail) { throw $fail }
